name: flutter_firebase_remote_config_demo
description: Flutter + Firebase Remote Config demo project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  cupertino_icons: ^1.0.8
  firebase_analytics: ^10.10.2
  firebase_core: ^2.30.0
  firebase_remote_config: ^4.4.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  package_info_plus: ^7.0.0
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
